=== GabryDMS2006/SEW/xml/etapa.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">

	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre_Etapa" />
				<xs:element ref="num_Etapa" />
				<xs:element ref="longitud_Etapa" />
				<xs:element ref="fecha" />
				<xs:element ref="tiempo_Ganador" />
				<xs:element ref="velocidad_Media_Ganador" />
				<xs:element ref="desnivel" />
				<xs:element ref="ciudad_Inicio" />
				<xs:element ref="ciudad_Fin" />
				<xs:element ref="tipo_Etapa" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="sonidos" />
				<xs:element ref="lugar_Salida" />
				<xs:element ref="lugar_Meta" />
				<xs:element ref="hitos_Importantes" />
				<xs:element ref="puntos_Anónimos" />
				<xs:element ref="clasificacion_Etapa" />
				<xs:element ref="clasificacion_General" />
				<xs:element ref="clasificacion_Equipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!--DATOS-->

	<xs:element name="nombre_Etapa" type="xs:string" />

	<xs:element name="num_Etapa">
		<xs:simpleType>
			<xs:restriction base="xs:nonNegativeInteger">
				<xs:minInclusive value="1" />
				<xs:maxInclusive value="21" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="longitud_Etapa">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="restriccion_longitud_etapa">
					<xs:attribute fixed="Km" name="unidadLongitud" type="xs:string"  use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>

	</xs:element>

	<xs:simpleType name="restriccion_longitud_etapa">
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="173.3"/>			
			</xs:restriction>
		</xs:simpleType>

	<xs:element name="fecha" type="xs:date" />
	<xs:element name="tiempo_Ganador" type="xs:duration" />

	<xs:element name="velocidad_Media_Ganador">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="restriccion_velocidad">
					<xs:attribute fixed="Km/h" name="unidadVelocidadMedia" type="xs:string"  use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="restriccion_velocidad">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="140" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="restriccion_desnivel">
					<xs:attribute fixed="m" name="unidadDesnivel" type="xs:string"  use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="restriccion_desnivel">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="6000" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="ciudad_Inicio" type="xs:string" />
	<xs:element name="ciudad_Fin" type="xs:string" />

	<xs:element name="tipo_Etapa">
		<xs:complexType>
			<xs:attribute name="tipo" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="llana" />
						<xs:enumeration value="montaña" />
						<xs:enumeration value="contrarreloj_individual" />
						<xs:enumeration value="contrarreloj_por_equipos" />
						<xs:enumeration value="media_montaña" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="referencia" minOccurs="3" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="referencia" type="xs:anyURI" />

	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="foto" minOccurs="1" maxOccurs="5" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="foto">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value=".+\.(jpg|png|jpeg|JPG|PNG|JPEG)" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="video" minOccurs="1" maxOccurs="3" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="video">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value=".+\.(mp4|mov|MOV|MP4)" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="sonidos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sonido" minOccurs="1" maxOccurs="3" />
			</xs:sequence>
		</xs:complexType>

	</xs:element>

	<xs:element name="sonido">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value=".+\.(mp3|MP3)" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="lugar_Salida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas_geograficas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lugar_Meta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas_geograficas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas_geograficas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="restriccion_longitud">
					<xs:attribute fixed="grados" name="unidadLongitud" type="xs:string"  use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="restriccion_longitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180" />
			<xs:maxInclusive value="180" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="restriccion_latitud">
					<xs:attribute fixed="grados" name="unidadLatitud" type="xs:string"  use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="restriccion_latitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90" />
			<xs:maxInclusive value="90" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="restriccion_altitud">
					<xs:attribute fixed="m" name="unidadAltitud" type="xs:string"  use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="restriccion_altitud">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="3000" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="hitos_Importantes">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="puerto_montaña" />
				<xs:element ref="sprint_intermedio" />
				<xs:element ref="sprint_bonificado" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="puerto_montaña">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas_geograficas" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="categoria" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="primera" />
						<xs:enumeration value="segunda" />
						<xs:enumeration value="tercera" />
						<xs:enumeration value="especial" />
						<xs:enumeration value="bonificado" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="sprint_intermedio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas_geograficas" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="sprint_bonificado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas_geograficas" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="restriccion_distancia">
					<xs:attribute fixed="Km" name="unidadDistancia" type="xs:string"  use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="restriccion_distancia">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="173.3" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="puntos_Anónimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="puntoAnónimo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="puntoAnónimo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas_geograficas" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificacion_Etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="primero">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ciclista" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="segundo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ciclista" />
				<xs:element ref="diferencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tercero">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ciclista" />
				<xs:element ref="diferencia" />
			</xs:sequence>
		</xs:complexType>

	</xs:element>
	<xs:element name="ciclista" type="xs:string" />
	<xs:element name="diferencia" type="xs:duration" />
	<xs:element name="clasificacion_General">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="clasificacion_Equipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primerEquipo" />
				<xs:element ref="segundoEquipo" />
				<xs:element ref="tercerEquipo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="primerEquipo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equipo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="segundoEquipo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equipo" />
				<xs:element ref="diferencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="tercerEquipo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equipo" />
				<xs:element ref="diferencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipo" type="xs:string" />

</xs:schema>

=== GabryDMS2006/SEW/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<etapa xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es etapa.xsd">

    <nombre_Etapa>Falset-Costa Daurada</nombre_Etapa>
    <num_Etapa>5</num_Etapa>
    <longitud_Etapa unidadLongitud="Km">173.3</longitud_Etapa>
    <fecha>2026-08-26</fecha>
    <tiempo_Ganador>PT3H47M2S</tiempo_Ganador>
    <velocidad_Media_Ganador unidadVelocidadMedia="Km/h">45.80</velocidad_Media_Ganador>
    <desnivel unidadDesnivel="m">1690</desnivel>
    <ciudad_Inicio>Falset-Costa Daurada</ciudad_Inicio>
    <ciudad_Fin>Roquetes. Terres De L'Ebre</ciudad_Fin>

    <tipo_Etapa tipo="media_montaña" /><!-- ONDULADA-->

    <referencias>

        <referencia>https://www.turismefalset.cat/costa-daurada/</referencia>
        <referencia>https://www.catalunya.com/es/continguts/territori/roquetes-2-1-572686</referencia>
        <referencia>https://www.ebre.com/es/roquetes/ </referencia>

    </referencias>

    <fotos>

        <foto>../multimedia/ciclistas.jpg</foto>
        <foto>../multimedia/imagenGandaor.jpg</foto>

    </fotos>

    <videos>

        <video>../multimedia/LaRuta2026.mp4</video>
        <video>../multimedia/Etapa5Highlights.mp4</video>

    </videos>

    <sonidos>

        <sonido>../multimedia/Etapa5_Podcast.mp3</sonido>
        <sonido>../multimedia/LaRuta2026_Etapa5.mp3</sonido>

    </sonidos>


    <lugar_Salida>

        <coordenadas_geograficas>

            <longitud unidadLongitud="grados">0.791409</longitud>
            <latitud unidadLatitud="grados">41.121371</latitud>
            <altitud unidadAltitud="m">267</altitud>

        </coordenadas_geograficas>

    </lugar_Salida>

    <lugar_Meta>

        <coordenadas_geograficas>

            <longitud unidadLongitud="grados">0.499001</longitud>
            <latitud unidadLatitud="grados">40.824104</latitud>
            <altitud unidadAltitud="m">22</altitud>

        </coordenadas_geograficas>

    </lugar_Meta>

    <hitos_Importantes>

        <puerto_montaña nombre="Puerto de Paüls" categoria="tercera">

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.4018</longitud>
                <latitud unidadLatitud="grados">40.9221</latitud>
                <altitud unidadAltitud="m">382</altitud>

            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">149</distancia>

        </puerto_montaña>

        <sprint_intermedio nombre="Tivenys">

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.510883</longitud>
                <latitud unidadLatitud="grados">40.904420</latitud>
                <altitud unidadAltitud="m">12</altitud>

            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">114.7</distancia>

        </sprint_intermedio>

    </hitos_Importantes>

    <puntos_Anónimos>

        <puntoAnónimo nombre="Els Guiamets Reservoir">

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.756641</longitud>
                <latitud unidadLatitud="grados"> 41.100820</latitud>
                <altitud unidadAltitud="m">217</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">5.33</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.704074</longitud>
                <latitud unidadLatitud="grados"> 41.113761</latitud>
                <altitud unidadAltitud="m">82</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">10.6</distancia>
        </puntoAnónimo>
        <puntoAnónimo nombre="Móra la Nova">

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.650397</longitud>
                <latitud unidadLatitud="grados"> 41.099806</latitud>
                <altitud unidadAltitud="m">36</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">16</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.663441</longitud>
                <latitud unidadLatitud="grados"> 41.069424</latitud>
                <altitud unidadAltitud="m">29</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">19.8</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.630273</longitud>
                <latitud unidadLatitud="grados"> 41.039276</latitud>
                <altitud unidadAltitud="m">25</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">25</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.603687</longitud>
                <latitud unidadLatitud="grados"> 41.002996</latitud>
                <altitud unidadAltitud="m">146</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">31.1</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.635254</longitud>
                <latitud unidadLatitud="grados"> 40.978148</latitud>
                <altitud unidadAltitud="m">146</altitud>

            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">35.2</distancia>
        </puntoAnónimo>
        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.657454</longitud>
                <latitud unidadLatitud="grados"> 40.932931</latitud>
                <altitud unidadAltitud="m">201</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">40.8</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.672423</longitud>
                <latitud unidadLatitud="grados">40.898454</latitud>
                <altitud unidadAltitud="m">246</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">44.9</distancia>
        </puntoAnónimo>

        <puntoAnónimo nombre="El Perelló">

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.715669</longitud>
                <latitud unidadLatitud="grados"> 40.877400</latitud>
                <altitud unidadAltitud="m">128</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">50.2</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.710915</longitud>
                <latitud unidadLatitud="grados"> 40.841410</latitud>
                <altitud unidadAltitud="m">71</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">55.0</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.689015</longitud>
                <latitud unidadLatitud="grados"> 40.803100</latitud>
                <altitud unidadAltitud="m">24</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">60.1</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.696608</longitud>
                <latitud unidadLatitud="grados"> 40.792167</latitud>
                <altitud unidadAltitud="m">0</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">61.8</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.711227</longitud>
                <latitud unidadLatitud="grados"> 40.729988</latitud>
                <altitud unidadAltitud="m">0</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">69.8</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.69046</longitud>
                <latitud unidadLatitud="grados"> 40.717604</latitud>
                <altitud unidadAltitud="m">0</altitud>

            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">74.8</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.607911</longitud>
                <latitud unidadLatitud="grados"> 40.703949</latitud>
                <altitud unidadAltitud="m">2</altitud>

            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">82.5</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.589370</longitud>
                <latitud unidadLatitud="grados"> 40.708154</latitud>
                <altitud unidadAltitud="m">3</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">84.2</distancia>
        </puntoAnónimo>

        <puntoAnónimo nombre="Amposta">

            <coordenadas_geograficas>

                <longitud unidadLongitud="grados">0.579744</longitud>
                <latitud unidadLatitud="grados"> 40.706084</latitud>
                <altitud unidadAltitud="m">8</altitud>
            </coordenadas_geograficas>

            <distancia unidadDistancia="Km">85.5</distancia>
        </puntoAnónimo>

        <puntoAnónimo>

            <coordenadas_geograficas>
